### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.nms.gpu_nms'

### ISSUE THREAD

**Issue by RebornL** [yqyao/YOLOv3_Pytorch#2]
hello, I meet this problem, I have executed make.sh. And There is a gpu_nms.pyx in the utils folder. This is the tracklog:
`
$ python train.py --input_wh 1024 1024 -b 64 --subdivisions 4 -d VOC --basenet ./weights/convert_darknet53.pth
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from model.yolo import Yolov3
  File "/home/gmy/lqb/YOLOv3_Pytorch/model/yolo.py", line 11, in <module>
    from utils.box_utils import permute_sigmoid, decode
  File "/home/gmy/lqb/YOLOv3_Pytorch/utils/box_utils.py", line 11, in <module>
    from utils.nms_wrapper import nms
  File "/home/gmy/lqb/YOLOv3_Pytorch/utils/nms_wrapper.py", line 9, in <module>
    from .nms.gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'utils.nms.gpu_nms'

`

**Comment by yqyao** [comment]
I am sorry for it, I forget to compile gpu.nms. I have updated the code. By the way, if you use anaconda3, maybe you need this https://github.com/rbgirshick/py-faster-rcnn/issues/706 when you compile the gpu nms.

**Comment by yqyao** [comment]
I am sorry for it, I forget to compile gpu.nms. I have updated the code. By the way, if you use anaconda3, maybe you need this https://github.com/rbgirshick/py-faster-rcnn/issues/706 when you compile the gpu nms. @RebornL

**Comment by RebornL** [comment]
Thanks for your reply! I have comment the gpu_nms function code, Beacuse I find that you just use cpu_nms function.@yqyao
